### ISSUE TITLE
error 2

### ISSUE THREAD

**Issue by atgaming0093** [Cyanic76/discord-modmail#12]
discord-modmail@1.0.0 start /home/runner/discord-modmail
> node bot.js

/home/runner/discord-modmail/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/runner/discord-modmail/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/home/runner/discord-modmail/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/runner/discord-modmail/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-modmail@1.0.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-modmail@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-06T07_40_08_320Z-debug.log
exit status 1

**Comment by Cyanic76** [comment]
Delete the folders where better-sqlite3 and quick.db are installed and run `npm install` or `npm install quick.db` again. [Related to this](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio/46384631#46384631)

**Comment by atgaming0093** [comment]
thanks bro worked

**Comment by Cyanic76** [comment]
Anytime, glad it's fixed!
