### ISSUE TITLE
TOKEN 

### ISSUE THREAD

**Issue by alex12266** [Cyanic76/discord-modmail#8]
I want to report the error that in the part of config.json there is no tocken option also if you try to put it in the file I do not recognize it

**Comment by Cyanic76** [comment]
You actually have to create a process.env file and set your token there (`TOKEN=Your token here`).

**Comment by alex12266** [comment]
SyntaxError: /home/runner/discord-modmail/config.json: Unexpected token } in JSON at position 157
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/discord-modmail/bot.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by Cyanic76** [comment]
There was an error in the json config file. I fixed that in the above commit, could you retry?

**Comment by Cyanic76** [comment]
Looks like a comma was missing, can you retry?
